--  CREAREA UNEI SECVENTE CE VA FI FOLOSITA IN INSERAREA INREGISTRARILOR IN TABELE

CREATE SEQUENCE MOTOR_SEQUENCE
    START WITH 1000;
CREATE SEQUENCE CARBURANT_SEQUENCE
    START WITH 1;
-- CREATE SEQUENCE MOTOR_CARBURANT_SEQUENCE
--     START WITH 1;
-- CREATE SEQUENCE MOTOR_ELECTRIC_SEQUENCE
--     START WITH 1;
CREATE SEQUENCE CAROSERIE_SEQUENCE
    START WITH 1;
CREATE SEQUENCE ADRESA_SEQUENCE
    START WITH 1;
CREATE SEQUENCE SHOWROOM_SEQUENCE
    START WITH 1;
CREATE SEQUENCE SHOWROOM_NUMERE_TELEFON_SEQUENCE
    START WITH 1;
CREATE SEQUENCE VEHICUL_SEQUENCE
    START WITH 1000000
    INCREMENT BY 10;
CREATE SEQUENCE ANGAJAT_SHOWROOM_SEQUENCE
    START WITH 1;
CREATE SEQUENCE MECANIC_SEQUENCE
    START WITH 1;
CREATE SEQUENCE VANZATOR_SEQUENCE
    START WITH 1;
CREATE SEQUENCE CLIENT_SEQUENCE
    START WITH 1;
CREATE SEQUENCE CLIENT_NUMERE_TELEFON_SEQUENCE
    START WITH 1;
CREATE SEQUENCE VEHICUL_DETINUT_CLIENT_SEQUENCE
    START WITH 1000000
    INCREMENT BY 10;
CREATE SEQUENCE PLATA_SEQUENCE
    START WITH 1;
CREATE SEQUENCE TRANZACTIE_SEQUENCE
    START WITH 1000000
    INCREMENT BY 7;
CREATE SEQUENCE SERVICE_SEQUENCE
    START WITH 1000000
    INCREMENT BY 7;



-- TABELA MOTOR

-- CREARE TABELA MOTOR
CREATE TABLE MOTOR
(
    ID_MOTOR INT PRIMARY KEY,
    MARCA VARCHAR(30),
    MODEL VARCHAR(30)
);

-- TABELA CARBURANT

-- CREARE TABELA CARBURANT
CREATE TABLE CARBURANT
(
    ID_CARBURANT INT PRIMARY KEY,
    TIP VARCHAR(30),
    VARIANTA VARCHAR(30),
    PRET_LITRU NUMBER(3,2),
    CONSTRAINT CHECK_PRET_LITRU CHECK (PRET_LITRU > 0),
    CONSTRAINT CHECK_TIP CHECK (TIP IN ('Benzina', 'Motorina'))
);

-- TABELA MOTOR_CARBURANT

-- CREARE TABELA MOTOR_CARBURANT
CREATE TABLE MOTOR_CARBURANT
(
    ID_MOTOR INT PRIMARY KEY,
    ID_CARBURANT INT,
    CAI_PUTERE INT,
    CAPACITATE_CILINDRICA_LITRI NUMBER(3,1),
    CONSUM_MEDIU_LITRI NUMBER(4,2),
    FOREIGN KEY (ID_MOTOR) REFERENCES MOTOR(ID_MOTOR),
    FOREIGN KEY (ID_CARBURANT) REFERENCES CARBURANT(ID_CARBURANT),
    CONSTRAINT CHECK_CAI_PUTERE_CARBURANT CHECK (CAI_PUTERE > 0),
    CONSTRAINT CHECK_CAPACITATE_CILINDRICA_LITRI CHECK (CAPACITATE_CILINDRICA_LITRI > 0),
    CONSTRAINT CHECK_CONSUM_MEDIU_LITRI CHECK (CONSUM_MEDIU_LITRI > 0)

);

-- TABELA MOTOR_ELECTRIC

-- CREARE TABELA MOTOR_ELECTRIC
CREATE TABLE MOTOR_ELECTRIC
(
    ID_MOTOR INT PRIMARY KEY,
    CAI_PUTERE INT,
    TIMP_INCARCARE_ORE NUMBER(3,2),
    AUTONOMIE_KM INT,
    FOREIGN KEY (ID_MOTOR) REFERENCES MOTOR(ID_MOTOR),
    CONSTRAINT CHECK_CAI_PUTERE_ELECTRIC CHECK (CAI_PUTERE > 0),
    CONSTRAINT CHECK_TIMP_INCARCARE_ORE CHECK (TIMP_INCARCARE_ORE > 0),
    CONSTRAINT CHECK_AUTONOMIE_KM CHECK (AUTONOMIE_KM > 0)
);

-- TABELA CAROSERIE

-- CREARE TABELA CAROSERIE
CREATE TABLE CAROSERIE
(
    ID_CAROSERIE INT PRIMARY KEY,
    NUME VARCHAR(30),
    NR_USI INT,
    NR_LOCURI INT,
    VOLUM_PORTBAGAJ_LITRI INT,
    CONSTRAINT CHECK_NR_USI CHECK (NR_USI > 0),
    CONSTRAINT CHECK_NR_LOCURI CHECK (NR_LOCURI > 0),
    CONSTRAINT CHECK_VOLUM_PORTBAGAJ_LITRI CHECK (VOLUM_PORTBAGAJ_LITRI > 0)
);

-- TABELA ADRESA

-- CREARE TABELA ADRESA
CREATE TABLE ADRESA
(
    ID_ADRESA INT PRIMARY KEY,
    STRADA VARCHAR(30),
    NR INT,
    ORAS VARCHAR(30),
    CONSTRAINT CHECK_NR_ADRESA CHECK (NR > 0)
);

-- TABELA SHOWROOM

-- CREARE TABELA SHOWROOM
CREATE TABLE SHOWROOM
(
    ID_SHOWROOM INT PRIMARY KEY,
    NUME VARCHAR(30),
    ID_ADRESA INT,
    FOREIGN KEY (ID_ADRESA) REFERENCES ADRESA(ID_ADRESA)
);

-- TABELA NUMERE_TELEFON_SHOWROOM

-- CREARE TABELA NUMERE_TELEFON_SHOWROOM
CREATE TABLE SHOWROOM_NUMERE_TELEFON
(
    ID_NUMAR INT PRIMARY KEY,
    ID_SHOWROOM INT,
    NR_TELEFON VARCHAR(30),
    CONSTRAINT CHECK_NR_TELEFON_SHOWROOM CHECK (NR_TELEFON LIKE '07________'),
    FOREIGN KEY (ID_SHOWROOM) REFERENCES SHOWROOM(ID_SHOWROOM)
);

-- TABELA VEHICUL

-- CREARE TABELA VEHICUL
CREATE TABLE VEHICUL
(
    ID_VEHICUL INT PRIMARY KEY,
    ID_SHOWROOM INT,
    ID_CAROSERIE INT,
    ID_MOTOR INT,
    MARCA VARCHAR(30),
    MODEL VARCHAR(30),
    AN_FABRICATIE INT,
    PRET NUMBER(10,2),
    FOREIGN KEY (ID_SHOWROOM) REFERENCES SHOWROOM(ID_SHOWROOM),
    FOREIGN KEY (ID_CAROSERIE) REFERENCES CAROSERIE(ID_CAROSERIE),
    FOREIGN KEY (ID_MOTOR) REFERENCES MOTOR(ID_MOTOR),
    CONSTRAINT CHECK_AN_FABRICATIE CHECK (AN_FABRICATIE > 0),
    CONSTRAINT CHECK_PRET CHECK (PRET > 0)
);

-- TABELA ANGAJAT_SHOWROOM

-- CREARE TABELA ANGAJAT_SHOWROOM
CREATE TABLE ANGAJAT_SHOWROOM
(
    ID_ANGAJAT INT PRIMARY KEY,
    ID_SHOWROOM INT,
    NUME VARCHAR(30),
    DATA_ANGAJARE DATE,
    SALARIU NUMBER(10,2),
    FOREIGN KEY (ID_SHOWROOM) REFERENCES SHOWROOM(ID_SHOWROOM),
    CONSTRAINT CHECK_SALARIU CHECK (SALARIU > 0)
);

-- TABELA MECANIC

-- CREARE TABELA MECANIC
CREATE TABLE MECANIC
(
    ID_ANGAJAT INT PRIMARY KEY,
    ID_SPECIALIZARE INT,
    FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJAT_SHOWROOM(ID_ANGAJAT),
    FOREIGN KEY (ID_SPECIALIZARE) REFERENCES MOTOR(ID_MOTOR)
);

-- TABELA VANZATOR

-- CREARE TABELA VANZATOR
CREATE TABLE VANZATOR
(
    ID_ANGAJAT INT PRIMARY KEY,
    ID_SPECIALIZARE INT,
    FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJAT_SHOWROOM(ID_ANGAJAT),
    FOREIGN KEY (ID_SPECIALIZARE) REFERENCES CAROSERIE(ID_CAROSERIE)
);

-- TABELA CLIENT

-- CREARE TABELA CLIENT
CREATE TABLE CLIENT
(
    ID_CLIENT INT PRIMARY KEY,
    NUME VARCHAR(30)
);

-- TABELA CLIENT_NUMERE_TELEFON

-- CREARE TABELA CLIENT_NUMERE_TELEFON
CREATE TABLE CLIENT_NUMERE_TELEFON
(
    ID_NUMAR INT PRIMARY KEY,
    ID_CLIENT INT,
    NR_TELEFON VARCHAR(30),
    CONSTRAINT CHECK_NR_TELEFON_CLIENTI CHECK (NR_TELEFON LIKE '07________'),
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
);

-- TABELA VEHICUL_DETINUT_CLIENT

-- CREARE TABELA VEHICUL_DETINUT_CLIENT
CREATE TABLE VEHICUL_DETINUT_CLIENT
(
    ID_VEHICUL INT PRIMARY KEY,
    ID_CLIENT INT,
    ID_CAROSERIE INT,
    ID_MOTOR INT,
    MARCA VARCHAR(30),
    MODEL VARCHAR(30),
    AN_FABRICATIE INT,
    NUMAR_INMATRICULARE VARCHAR(30) UNIQUE,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    FOREIGN KEY (ID_CAROSERIE) REFERENCES CAROSERIE(ID_CAROSERIE),
    FOREIGN KEY (ID_MOTOR) REFERENCES MOTOR(ID_MOTOR),
    CONSTRAINT CHECK_AN_FABRICATIE_VEHICUL_DETINUT_CLIENT CHECK (AN_FABRICATIE > 0),
    CONSTRAINT CHECK_NUMAR_INAMTRICULARE CHECK
    (
        REGEXP_LIKE(NUMAR_INMATRICULARE, '^(AB|AR|AG|B|BC|BH|BN|BR|BZ|CS|CL|CJ|CT|CV|DB|DJ|GL|GR|GJ|HR|HD|IL|IS|IF|MM|MH|MS|NT|OT|PH|SM|SJ|SB|SV|TR|TM|TL|VS|VL|VN|CD|CO|TC) [0-9]{2,3} [A-Z]{3}$')
    )
);

-- TABELA PLATA

-- CREARE TABELA PLATA
CREATE TABLE PLATA
(
    ID_PLATA INT PRIMARY KEY,
    ID_CLIENT INT,
    SUMA NUMBER(10,2),
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    CONSTRAINT CHECK_SUMA CHECK (SUMA > 0)
);

-- TABELA TRANZACTIE

-- CREARE TABELA TRANZACTIE
CREATE TABLE TRANZACTIE
(
    ID_TRANZACTIE INT PRIMARY KEY,
    ID_CLIENT INT,
    ID_VEHICUL INT,
    ID_ANGAJAT INT,
    DATA_TRANZACTIE DATE,
    SUMA NUMBER(10,2),
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    FOREIGN KEY (ID_VEHICUL) REFERENCES VEHICUL(ID_VEHICUL),
    FOREIGN KEY (ID_ANGAJAT) REFERENCES VANZATOR(ID_ANGAJAT),
    CONSTRAINT CHECK_SUMA_TRANZACTIE CHECK (SUMA > 0)
);

-- TABELA SERVICE

-- CREARE TABELA SERVICE
CREATE TABLE SERVICE
(
    ID_SERVICE INT PRIMARY KEY,
    ID_ANGAJAT INT,
    ID_VEHICUL INT,
    ID_PLATA INT,
    FOREIGN KEY (ID_ANGAJAT) REFERENCES MECANIC(ID_ANGAJAT),
    FOREIGN KEY (ID_VEHICUL) REFERENCES VEHICUL_DETINUT_CLIENT(ID_VEHICUL),
    FOREIGN KEY (ID_PLATA) REFERENCES PLATA(ID_PLATA)
);














