DROP TABLE MOTOR_ELECTRIC;
DROP TABLE MOTOR_CARBURANT;
DROP TABLE MOTOR;
DROP TABLE CARBURANT;

-- TABELA MOTOR

CREATE TABLE MOTOR
(
    ID_MOTOR INT PRIMARY KEY,
    MARCA VARCHAR(30),
    MODEL VARCHAR(30)
);

-- TABELA CARBURANT

CREATE TABLE CARBURANT
(
    ID_CARBURANT INT PRIMARY KEY,
    TIP VARCHAR(30),
    VARIANTA VARCHAR(30),
    PRET_LITRU FLOAT,
    CONSTRAINT CHECK_PRET_LITRU CHECK (PRET_LITRU > 0),
    CONSTRAINT CHECK_TIP CHECK (TIP IN ('Benzina', 'Motorina'))
);

-- TABELA MOTOR_CARBURANT

CREATE TABLE MOTOR_CARBURANT
(
    ID_MOTOR INT PRIMARY KEY,
    ID_CARBURANT INT,
    CAI_PUTERE INT,
    CAPACITATE_CILINDRICA_LITRI FLOAT,
    CONSUM_MEDIU_LITRI FLOAT,
    FOREIGN KEY (ID_MOTOR) REFERENCES MOTOR(ID_MOTOR),
    FOREIGN KEY (ID_CARBURANT) REFERENCES CARBURANT(ID_CARBURANT),
    CONSTRAINT CHECK_CAI_PUTERE_CARBURANT CHECK (CAI_PUTERE > 0),
    CONSTRAINT CHECK_CAPACITATE_CILINDRICA_LITRI CHECK (CAPACITATE_CILINDRICA_LITRI > 0),
    CONSTRAINT CHECK_CONSUM_MEDIU_LITRI CHECK (CONSUM_MEDIU_LITRI > 0)

);

-- TABELA MOTOR_ELECTRIC

CREATE TABLE MOTOR_ELECTRIC
(
    ID_MOTOR INT PRIMARY KEY,
    CAI_PUTERE INT,
    TIMP_INCARCARE_ORE FLOAT,
    AUTONOMIE_KM INT,
    FOREIGN KEY (ID_MOTOR) REFERENCES MOTOR(ID_MOTOR),
    CONSTRAINT CHECK_CAI_PUTERE_ELECTRIC CHECK (CAI_PUTERE > 0),
    CONSTRAINT CHECK_TIMP_INCARCARE_ORE CHECK (TIMP_INCARCARE_ORE > 0),
    CONSTRAINT CHECK_AUTONOMIE_KM CHECK (AUTONOMIE_KM > 0)
);

-- TABELA CAROSERIE

CREATE TABLE CAROSERIE
(
    ID_CAROSERIE INT PRIMARY KEY,
    NUME VARCHAR(30),
    NR_USI INT,
    NR_LOCURI INT,
    VOLUM_PORTBAGAJ_LITRI INT,
    CONSTRAINT CHECK_NR_USI CHECK (NR_USI > 0),
    CONSTRAINT CHECK_NR_LOCURI CHECK (NR_LOCURI > 0),
    CONSTRAINT CHECK_VOLUM_PORTBAGAJ_LITRI CHECK (VOLUM_PORTBAGAJ_LITRI > 0)
);

-- TABELA SHOWROOM

CREATE TABLE SHOWROOM
(
    ID_SHOWROOM INT PRIMARY KEY,
    NUME VARCHAR(30),
    ID_ADRESA INT
);

-- TABELA NUMERE_TELEFON_SHOWROOM

CREATE TABLE SHOWROOM_NUMERE_TELEFON
(
    ID_NUMAR INT PRIMARY KEY,
    ID_SHOWROOM INT,
    NR_TELEFON VARCHAR(30),
    CONSTRAINT CHECK_NR_TELEFON_SHOWROOM CHECK (NR_TELEFON LIKE '07________'),
    FOREIGN KEY (ID_SHOWROOM) REFERENCES SHOWROOM(ID_SHOWROOM)
);

-- TABELA VEHICUL

CREATE TABLE VEHICUL
(
    ID_VEHICUL INT PRIMARY KEY,
    ID_SHOWROOM INT,
    ID_CAROSERIE INT,
    ID_MOTOR INT,
    MARCA VARCHAR(30),
    MODEL VARCHAR(30),
    AN_FABRICATIE INT,
    PRET FLOAT,
    FOREIGN KEY (ID_SHOWROOM) REFERENCES SHOWROOM(ID_SHOWROOM),
    FOREIGN KEY (ID_CAROSERIE) REFERENCES CAROSERIE(ID_CAROSERIE),
    FOREIGN KEY (ID_MOTOR) REFERENCES MOTOR(ID_MOTOR),
    CONSTRAINT CHECK_AN_FABRICATIE CHECK (AN_FABRICATIE > 0),
    CONSTRAINT CHECK_PRET CHECK (PRET > 0)
);

-- TABELA ANGAJAT_SHOWROOM

CREATE TABLE ANGAJAT_SHOWROOM
(
    ID_ANGAJAT INT PRIMARY KEY,
    ID_SHOWROOM INT,
    NUME VARCHAR(30),
    DATA_ANGAJARE DATE,
    SALARIU FLOAT,
    FOREIGN KEY (ID_SHOWROOM) REFERENCES SHOWROOM(ID_SHOWROOM),
    CONSTRAINT CHECK_SALARIU CHECK (SALARIU > 0)
);

-- TABELA MECANIC

CREATE TABLE MECANIC
(
    ID_ANGAJAT INT PRIMARY KEY,
    ID_SPECIALIZARE INT,
    FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJAT_SHOWROOM(ID_ANGAJAT),
    FOREIGN KEY (ID_SPECIALIZARE) REFERENCES MOTOR(ID_MOTOR)
);

-- TABELA VANZATOR

CREATE TABLE VANZATOR
(
    ID_ANGAJAT INT PRIMARY KEY,
    ID_SPECIALIZARE INT,
    FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJAT_SHOWROOM(ID_ANGAJAT),
    FOREIGN KEY (ID_SPECIALIZARE) REFERENCES CAROSERIE(ID_CAROSERIE)
);

-- TABELA CLIENT

CREATE TABLE CLIENT
(
    ID_CLIENT INT PRIMARY KEY,
    NUME VARCHAR(30)
);

-- TABELA NUMERE_TELEFON_CLIENTI

CREATE TABLE CLIENTI_NUMERE_TELEFON
(
    ID_NUMAR INT PRIMARY KEY,
    ID_CLIENT INT,
    NR_TELEFON VARCHAR(30),
    CONSTRAINT CHECK_NR_TELEFON_CLIENTI CHECK (NR_TELEFON LIKE '07________'),
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
);

-- TABELA VEHICUL_DETINUT_CLIENT

CREATE TABLE VEHICUL_DETINUT_CLIENT
(
    ID_VEHICUL INT PRIMARY KEY,
    ID_CLIENT INT,
    ID_CAROSERIE INT,
    ID_MOTOR INT,
    MARCA VARCHAR(30),
    MODEL VARCHAR(30),
    AN_FABRICATIE INT,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    FOREIGN KEY (ID_CAROSERIE) REFERENCES CAROSERIE(ID_CAROSERIE),
    FOREIGN KEY (ID_MOTOR) REFERENCES MOTOR(ID_MOTOR),
    CONSTRAINT CHECK_AN_FABRICATIE_VEHICUL_DETINUT_CLIENT CHECK (AN_FABRICATIE > 0)
);

-- TABELA PLATA

CREATE TABLE PLATA
(
    ID_PLATA INT PRIMARY KEY,
    ID_CLIENT INT,
    SUMA FLOAT,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    CONSTRAINT CHECK_SUMA CHECK (SUMA > 0)
);

-- TABELA TRANZACTIE

CREATE TABLE TRANZACTIE
(
    ID_TRANZACTIE INT PRIMARY KEY,
    ID_CLIENT INT,
    ID_VEHICUL INT,
    ID_ANGAJAT INT,
    DATA_TRANZACTIE DATE,
    SUMA FLOAT,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    FOREIGN KEY (ID_VEHICUL) REFERENCES VEHICUL(ID_VEHICUL),
    FOREIGN KEY (ID_ANGAJAT) REFERENCES VANZATOR(ID_ANGAJAT),
    CONSTRAINT CHECK_SUMA_TRANZACTIE CHECK (SUMA > 0)
);

-- TABELA SERVICE

CREATE TABLE SERVICE
(
    ID_SERVICE INT PRIMARY KEY,
    ID_ANGAJAT INT,
    ID_VEHICUL INT,
    ID_PLATA INT,
    FOREIGN KEY (ID_ANGAJAT) REFERENCES MECANIC(ID_ANGAJAT),
    FOREIGN KEY (ID_VEHICUL) REFERENCES VEHICUL_DETINUT_CLIENT(ID_VEHICUL),
    FOREIGN KEY (ID_PLATA) REFERENCES PLATA(ID_PLATA)
);
















